networks:
  hadoop_net:
    driver: bridge

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=ticket_cluster
    env_file:
      - ./docker/hadoop.env
    volumes:
      - ./data:/ticket_system_local
      - ./scripts:/scripts
      - ./jobs:/jobs
    networks:
      - hadoop_net

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    hostname: resourcemanager
    restart: always
    ports:
      - "8088:8088"
    environment:
      - SERVICE_PRECONDITION=namenode:9000
    env_file:
      - ./docker/hadoop.env
    networks:
      - hadoop_net

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-1
    hostname: datanode-1
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9000
    env_file:
      - ./docker/hadoop.env
    networks:
      - hadoop_net

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-2
    hostname: datanode-2
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9000
    env_file:
      - ./docker/hadoop.env
    networks:
      - hadoop_net

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-3
    hostname: datanode-3
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9000
    env_file:
      - ./docker/hadoop.env
    networks:
      - hadoop_net

  datanode4:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-4
    hostname: datanode-4
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9000
    env_file:
      - ./docker/hadoop.env
    networks:
      - hadoop_net

  datanode5:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-5
    hostname: datanode-5
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9000
    env_file:
      - ./docker/hadoop.env
    networks:
      - hadoop_net

  datanode6:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-6
    hostname: datanode-6
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9000
    env_file:
      - ./docker/hadoop.env
    networks:
      - hadoop_net

  datanode7:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-7
    hostname: datanode-7
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9000
    env_file:
      - ./docker/hadoop.env
    networks:
      - hadoop_net

  datanode8:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-8
    hostname: datanode-8
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9000
    env_file:
      - ./docker/hadoop.env
    networks:
      - hadoop_net

  datanode9:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-9
    hostname: datanode-9
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9000
    env_file:
      - ./docker/hadoop.env
    networks:
      - hadoop_net

  datanode10:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-10
    hostname: datanode-10
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9000
    env_file:
      - ./docker/hadoop.env
    networks:
      - hadoop_net
  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    hostname: nodemanager
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9000 resourcemanager:8088
    env_file:
      - ./docker/hadoop.env
    ports:
      - "8042:8042"
    networks:
      - hadoop_net

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    hostname: historyserver
    restart: always
    ports:
      - "8188:8188"
    environment:
      - SERVICE_PRECONDITION=namenode:9000 resourcemanager:8088
    env_file:
      - ./docker/hadoop.env
    networks:
      - hadoop_net


  spark-master:
    image: bde2020/spark-master:3.0.0-hadoop3.2
    container_name: spark-master
    hostname: spark-master
    restart: always
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./docker/hadoop.env
    volumes:
      - ./jobs:/jobs
      - ./scripts:/scripts
      - ./data:/data
    networks:
      - hadoop_net

  spark-worker:
    image: bde2020/spark-worker:3.0.0-hadoop3.2
    container_name: spark-worker
    hostname: spark-worker
    restart: always
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./docker/hadoop.env
    volumes:
      - ./jobs:/jobs
      - ./scripts:/scripts
      - ./data:/data
    networks:
      - hadoop_net

