networks:
  hadoop_net:
    driver: bridge

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=ticket_cluster
    env_file:
      - ./docker/hadoop.env
    volumes:
      - ./data:/ticket_system_local
      - ./scripts:/scripts
    networks:
      - hadoop_net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9000
    env_file:
      - ./docker/hadoop.env
    networks:
      - hadoop_net

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    hostname: resourcemanager
    restart: always
    ports:
      - "8088:8088"
    environment:
      - SERVICE_PRECONDITION=namenode:9000
    env_file:
      - ./docker/hadoop.env
    networks:
      - hadoop_net
